// CSSI server gRPC API.
//
// The CSI driver talks to the CSSI storage server over this service.
// The server owns one LVM Volume Group on a Linux host; for each request
// it carves a Logical Volume out of that VG, formats it with the requested
// filesystem, and returns an opaque volume handle the driver later uses to
// mount the resulting NFS export.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/cssi/v1/cssi.proto

package cssiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateVolumeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable, caller-chosen identity for the volume. Acts as the
	// idempotency key: re-issuing CreateVolume with the same name and the
	// same other fields must return the same volume_handle and success.
	// Re-issuing with the same name but different fields is a conflict.
	// The CSI driver forwards the CSI-level volume name here (typically
	// "pvc-<PVC.UID>"), which is stable across external-provisioner
	// retries.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Capacity in bytes for the new LV.
	SizeBytes int64 `protobuf:"varint,2,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	// Filesystem to create on the LV (e.g. "ext4", "xfs").
	FsType        string `protobuf:"bytes,3,opt,name=fs_type,json=fsType,proto3" json:"fs_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVolumeRequest) Reset() {
	*x = CreateVolumeRequest{}
	mi := &file_proto_cssi_v1_cssi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVolumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVolumeRequest) ProtoMessage() {}

func (x *CreateVolumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cssi_v1_cssi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVolumeRequest.ProtoReflect.Descriptor instead.
func (*CreateVolumeRequest) Descriptor() ([]byte, []int) {
	return file_proto_cssi_v1_cssi_proto_rawDescGZIP(), []int{0}
}

func (x *CreateVolumeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateVolumeRequest) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *CreateVolumeRequest) GetFsType() string {
	if x != nil {
		return x.FsType
	}
	return ""
}

type CreateVolumeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True when the LV was created, formatted, and exported.
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Human-readable failure reason; empty on success.
	Reason string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	// Opaque handle the driver later passes back when mounting the volume.
	VolumeHandle  string `protobuf:"bytes,3,opt,name=volume_handle,json=volumeHandle,proto3" json:"volume_handle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVolumeResponse) Reset() {
	*x = CreateVolumeResponse{}
	mi := &file_proto_cssi_v1_cssi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVolumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVolumeResponse) ProtoMessage() {}

func (x *CreateVolumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cssi_v1_cssi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVolumeResponse.ProtoReflect.Descriptor instead.
func (*CreateVolumeResponse) Descriptor() ([]byte, []int) {
	return file_proto_cssi_v1_cssi_proto_rawDescGZIP(), []int{1}
}

func (x *CreateVolumeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateVolumeResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *CreateVolumeResponse) GetVolumeHandle() string {
	if x != nil {
		return x.VolumeHandle
	}
	return ""
}

var File_proto_cssi_v1_cssi_proto protoreflect.FileDescriptor

const file_proto_cssi_v1_cssi_proto_rawDesc = "" +
	"\n" +
	"\x18proto/cssi/v1/cssi.proto\x12\acssi.v1\"a\n" +
	"\x13CreateVolumeRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x02 \x01(\x03R\tsizeBytes\x12\x17\n" +
	"\afs_type\x18\x03 \x01(\tR\x06fsType\"m\n" +
	"\x14CreateVolumeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12#\n" +
	"\rvolume_handle\x18\x03 \x01(\tR\fvolumeHandle2V\n" +
	"\aStorage\x12K\n" +
	"\fCreateVolume\x12\x1c.cssi.v1.CreateVolumeRequest\x1a\x1d.cssi.v1.CreateVolumeResponseB2Z0github.com/michaelcourcyo/cssi/pkg/api/v1;cssiv1b\x06proto3"

var (
	file_proto_cssi_v1_cssi_proto_rawDescOnce sync.Once
	file_proto_cssi_v1_cssi_proto_rawDescData []byte
)

func file_proto_cssi_v1_cssi_proto_rawDescGZIP() []byte {
	file_proto_cssi_v1_cssi_proto_rawDescOnce.Do(func() {
		file_proto_cssi_v1_cssi_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_cssi_v1_cssi_proto_rawDesc), len(file_proto_cssi_v1_cssi_proto_rawDesc)))
	})
	return file_proto_cssi_v1_cssi_proto_rawDescData
}

var file_proto_cssi_v1_cssi_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_cssi_v1_cssi_proto_goTypes = []any{
	(*CreateVolumeRequest)(nil),  // 0: cssi.v1.CreateVolumeRequest
	(*CreateVolumeResponse)(nil), // 1: cssi.v1.CreateVolumeResponse
}
var file_proto_cssi_v1_cssi_proto_depIdxs = []int32{
	0, // 0: cssi.v1.Storage.CreateVolume:input_type -> cssi.v1.CreateVolumeRequest
	1, // 1: cssi.v1.Storage.CreateVolume:output_type -> cssi.v1.CreateVolumeResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_cssi_v1_cssi_proto_init() }
func file_proto_cssi_v1_cssi_proto_init() {
	if File_proto_cssi_v1_cssi_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_cssi_v1_cssi_proto_rawDesc), len(file_proto_cssi_v1_cssi_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_cssi_v1_cssi_proto_goTypes,
		DependencyIndexes: file_proto_cssi_v1_cssi_proto_depIdxs,
		MessageInfos:      file_proto_cssi_v1_cssi_proto_msgTypes,
	}.Build()
	File_proto_cssi_v1_cssi_proto = out.File
	file_proto_cssi_v1_cssi_proto_goTypes = nil
	file_proto_cssi_v1_cssi_proto_depIdxs = nil
}
